<?php

function mao_help($path, $arg) {

  switch ($path) {
    case "admin/help#mao":
      return '<p>'.  t("A module created to show how to create modules") .'</p>';
      break;
  }
}

/**
* Implements hook_menu().
*/
function mao_menu() {
  $items = array();

  $items['admin/config/content/mao'] = array(
    'title' => 'Mao na Massa',
    'description' => 'Configuration for Mao na Massa',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mao_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'mao.admin.inc'
  );

  $items['mao/page'] = array(
    'title' => 'Mao na Massa',
    'description' => 'Simple content',
    'page callback' => 'mao_page_simple',
    'access arguments' => array('access mao page'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'mao.pages.inc',
    'menu_name' => 'main-menu'
  );

  $items['node/%node/mao'] = array(
    'title' => 'Mao na Massa',
    'description' => 'Tab item',
    'page callback' => 'mao_page_tab',
    'page arguments' => array(1),
    'access arguments' => array('access mao page'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'mao.pages.inc',
    'menu_name' => 'main-menu'
  );

  return $items;
}

/**
* Implements hook_block_info().
*/
function mao_block_info() {
  $blocks['mao'] = array(
    'info' => t('Mao na Massa'),
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*
* Prepares the contents of the block.
*/
function mao_block_view($delta = '') {
  $block = array();
  switch($delta){
    case 'mao':
      if (user_access('view mao na massa side block')) {
        $block['subject'] = t('Current posts');
        $result = mao_contents();
        $items = array();
        foreach ($result as $node){
          $items[] = array(
            'data' => l($node->title, 'node/' . $node->nid),
          );
        }

        if (empty($items)) {
          $block['content'] = t('No posts available.');
        }
        else {
          $block['content'] = theme('item_list', array('items' => $items));
        }

      }
  }
  return $block;
}

function mao_contents(){
  $max_num = variable_get('mao_max', 3);
  $content_type = variable_get('mao_type', 0);

  if ($content_type) {
    $query = db_select('node', 'n')
      ->fields('n', array('nid', 'title', 'created'))
      ->condition('status', 1)
      ->condition('type', $content_type)
      ->orderBy('created', 'DESC')
      ->range(0, $max_num)
      ->execute();
  } else {
    $query = db_select('node', 'n')
      ->fields('n', array('nid', 'title', 'created'))
      ->condition('status', 1)
      ->orderBy('created', 'DESC')
      ->range(0, $max_num)
      ->execute();
  }

  return $query;
}

function mao_block_configure($delta = '') {

  $form = array();
  if ($delta == 'mao') {
    $form['mao_max'] = array(
      '#type' => 'textfield',
      '#title' => t('Items to display'),
      '#size' => 3,
      '#description' => t('How much itens to display.'),
      '#default_value' => variable_get('mao_max',  t('3')),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 *
 * This hook declares how the configured options for a block
 * provided by this module are saved.
 */
function mao_block_save($delta = '', $edit = array()) {
  if ($delta == 'mao') {
    variable_set('mao_max', $edit['mao_max']);
  }
  return;
}


function mao_permission() {
  return array(
    'view mao na massa side block' => array(
      'title' => t('View the Mao na Massa side block'),
      'description' => t('May view the side block.'),
    ),
  );
}
